### ISSUE TITLE
使用keras/theano加入激活函数L2正则时报告scalar错误

### ISSUE THREAD

**Issue by boozyguo** [MoyanZitto/keras-cn#3]
when using “activity_regularizer” in keras with theno backend, some error report:

Traceback (most recent call last):
File "D:/working/AI/keras/snn/deepS/sys/deeps_mlp.py", line 238, in 
validation_data=(x_test, y_test))
File "C:\Anaconda2\lib\site-packages\keras\models.py", line 429, in fit
sample_weight=sample_weight)
File "C:\Anaconda2\lib\site-packages\keras\engine\training.py", line 1081, in fit
self._make_train_function()
File "C:\Anaconda2\lib\site-packages\keras\engine\training.py", line 698, in _make_train_function
training_updates = self.optimizer.get_updates(trainable_weights, self.constraints, self.total_loss)
File "C:\Anaconda2\lib\site-packages\keras\optimizers.py", line 321, in get_updates
grads = self.get_gradients(loss, params)
File "C:\Anaconda2\lib\site-packages\keras\optimizers.py", line 53, in get_gradients
grads = K.gradients(loss, params)
File "C:\Anaconda2\lib\site-packages\keras\backend\theano_backend.py", line 576, in gradients
return T.grad(loss, variables)
File "C:\Anaconda2\lib\site-packages\theano\gradient.py", line 436, in grad
raise TypeError("cost must be a scalar.")
TypeError: cost must be a scalar.

The model is very simple:

keras.regularizers.WeightRegularizer(l1=0.01, l2=0.01)
keras.regularizers.ActivityRegularizer(l1=0.01, l2=0.01)

model = Sequential()
model.add(Dense(16, input_shape=(inputsize,),W_regularizer=l1l2(0.01,0.01),b_regularizer=l1l2(0.01,0.01)))
model.add(Activation('relu'))
model.add(Dropout(0.8))

model.add(Dense(1,W_regularizer=l1l2(0.01,0.01),b_regularizer=l1l2(0.01,0.01),activity_regularizer=activity_l1l2(0.01,0.01)))
model.add(Activation('sigmoid'))

model.summary()

so, how can i use the "activity_regularizer" ?

**Comment by MoyanZitto** [comment]
Is this your full code? If possible pls paste your full code with line numbers.
btw, Chinese is avaiable to us.

**Comment by boozyguo** [comment]
完整代码如下，是一个2分类问题：

import numpy as np

from keras.datasets import cifar10
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten,BatchNormalization,noise,LSTM,Embedding,GRU,SimpleRNN
from keras.layers import Convolution2D, MaxPooling2D, Convolution1D,AveragePooling2D,Merge,RepeatVector,Lambda
from keras.optimizers import SGD, Adam, RMSprop
from keras.utils import np_utils
from keras.layers.advanced_activations import PReLU, SReLU,ELU,LeakyReLU
from keras.layers.noise import GaussianNoise
from keras.constraints import maxnorm,unitnorm,nonneg

from keras import backend as k
from keras.regularizers import l1l2, l2, activity_l1l2,activity_l2
from keras.callbacks import EarlyStopping
from keras.callbacks import ModelCheckpoint

from keras.models import model_from_json
import h5py
import os

from keras.utils.layer_utils import layer_from_config
import pandas as pd
import keras
import random

batch_size = 128
nb_classes = 1
nb_epoch = 100000
learnrate = 5e-7
inputsize = 12

train_data_predict_results = "..\data\20160920\txt\results\train_results.csv"
test_data_predict_results = "..\data\20160920\txt\results\test_results.csv"

#############################################
traindatadir = "..\data\20160920\txt\test_train"
traindatafilename = "traindata"
train_shd=pd.read_csv(traindatadir+'\'+traindatafilename+'.csv')

shd = train_shd.values
train_items_len = len(shd)
print (train_items_len)
y_train = shd[:,2]
x_train = shd[:,3:3+inputsize]

for steps in range(0,inputsize):
    x_train[:,steps] -= (x_train[:,steps].min() - 1e-7)
    x_train[:,steps] /= (x_train[:,steps].max() + 1e-7)
    x_train[:,steps] -= x_train[:,steps].mean()
    x_train[:,steps] /= (x_train[:,steps].std() + 1e-7 )

print ('train mean and std')
print (x_train.mean())
print (x_train.std())
print (x_train.max())
print (x_train.min())

x_train = x_train.reshape(train_items_len,inputsize)
y_train = y_train.reshape(train_items_len,1)

print(x_train.shape, 'train samples')
print(y_train.shape, 'train samples')
x_train = x_train.astype('float32')
y_train = y_train.astype('float32')
print (x_train[0:5])
print (y_train[0:5])

##############################################
testdatadir = "..\data\20160920\txt\test_test"
testdatafilename = "testdata"
resultsfilename="testresults"
test_shd=pd.read_csv(testdatadir+'\'+testdatafilename+'.csv')

td = test_shd.values
test_items_len = len(td)
print (test_items_len)
y_test = td[:,2]
x_test = td[:,3:3+inputsize]

for steps in range(0,inputsize):
    x_test[:,steps] -= (x_test[:,steps].min() - 1e-7)
    x_test[:,steps] /= (x_test[:,steps].max() + 1e-7)
    x_test[:,steps] -= x_test[:,steps].mean()
    x_test[:,steps] /= (x_test[:,steps].std() + 1e-7 )

print ('train mean and std')
print (x_train.mean())
print (x_train.std())
print (x_train.max())
print (x_train.min())

x_test = x_test.reshape(test_items_len,inputsize)
y_test = y_test.reshape(test_items_len,1)

x_test = x_test.astype('float64')
y_test = y_test.astype('float64')
print(x_test.shape, 'test samples')
print(y_test.shape, 'test samples')
##############################################

keras.regularizers.WeightRegularizer(l1=0.01, l2=0.01)
keras.regularizers.ActivityRegularizer(l1=0.01, l2=0.01)

model = Sequential()
model.add(Dense(16, input_shape=(inputsize,),W_regularizer=l1l2(0.01,0.01),b_regularizer=l1l2(0.01,0.01)))
model.add(Activation('relu'))
model.add(Dropout(0.8))

model.add(Dense(1,W_regularizer=l1l2(0.01,0.01),b_regularizer=l1l2(0.01,0.01),activity_regularizer=activity_l1l2(0.01,0.01)))
model.add(Activation('sigmoid'))

model.summary()

model.compile(loss='mean_absolute_error',  #categorical_crossentropy, mean_absolute_error,binary_crossentropy
              optimizer=Adam(lr=learnrate),    #RMSprop,Adam
              metrics=['accuracy'])

history = model.fit(x_train, y_train,
                    batch_size=batch_size, nb_epoch=nb_epoch,
                    verbose=1,
                    validation_data=(x_test, y_test))
score = model.evaluate(x_test, y_test, verbose=0)
print('Test score:', score[0])
print('Test accuracy:', score[1])

运行时打印和报错为：
C:\Anaconda2\python.exe D:/working/AI/keras/snn/deepS/sys/deeps_mlp_github.py
Using Theano backend.
42211
train mean and std
-5.22518771526e-15
0.999998770886
24.8719490178
-1.44113335709
(42211L, 12L) train samples
(42211L, 1L) train samples
[[-1.33593607 -1.3338784  -1.31996691 -1.34842169 -0.29707187 -0.30956835
  -1.33528137 -1.34045124 -1.32070458 -1.3522172  -0.24597032 -0.29436523]
 [-1.33593607 -1.3338784  -1.31996691 -1.34692633 -0.30467248 -0.31193861
  -1.33528137 -1.33318746 -1.319296   -1.34773314 -0.29701415 -0.3096078 ]
 [-1.33593607 -1.3338784  -1.32137609 -1.34842169 -0.37678945 -0.33446258
  -1.33528137 -1.33318746 -1.319296   -1.34623837 -0.30461395 -0.31197768]
 [-1.33303177 -1.33533192 -1.32137609 -1.34692633 -0.31141478 -0.31403792
  -1.33528137 -1.33318746 -1.32070458 -1.34773314 -0.3767235  -0.33449784]
 [-1.33012736 -1.332425   -1.31433022 -1.34393573 -0.03539136 -0.22610563
  -1.33237815 -1.33464015 -1.32070458 -1.34623837 -0.31135556 -0.31407663]]
[[ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]]
5336
train mean and std
1.08447e-09
0.999999
24.8719
-1.44113
(5336L, 12L) test samples
(5336L, 1L) test samples

---

# Layer (type)                     Output Shape          Param #     Connected to                     

dense_1 (Dense)                  (None, 16)            208         dense_input_1[0][0]              

---

activation_1 (Activation)        (None, 16)            0           dense_1[0][0]                    

---

dropout_1 (Dropout)              (None, 16)            0           activation_1[0][0]               

---

dense_2 (Dense)                  (None, 1)             17          dropout_1[0][0]                  

---

# activation_2 (Activation)        (None, 1)             0           dense_2[0][0]                    

Total params: 225

---

Traceback (most recent call last):
  File "D:/working/AI/keras/snn/deepS/sys/deeps_mlp_github.py", line 129, in <module>
    validation_data=(x_test, y_test))
  File "C:\Anaconda2\lib\site-packages\keras\models.py", line 429, in fit
    sample_weight=sample_weight)
  File "C:\Anaconda2\lib\site-packages\keras\engine\training.py", line 1081, in fit
    self._make_train_function()
  File "C:\Anaconda2\lib\site-packages\keras\engine\training.py", line 698, in _make_train_function
    training_updates = self.optimizer.get_updates(trainable_weights, self.constraints, self.total_loss)
  File "C:\Anaconda2\lib\site-packages\keras\optimizers.py", line 321, in get_updates
    grads = self.get_gradients(loss, params)
  File "C:\Anaconda2\lib\site-packages\keras\optimizers.py", line 53, in get_gradients
    grads = K.gradients(loss, params)
  File "C:\Anaconda2\lib\site-packages\keras\backend\theano_backend.py", line 576, in gradients
    return T.grad(loss, variables)
  File "C:\Anaconda2\lib\site-packages\theano\gradient.py", line 436, in grad
    raise TypeError("cost must be a scalar.")
TypeError: cost must be a scalar.

Process finished with exit code 1

**Comment by MoyanZitto** [comment]
问题在于你的loss function不对，理论上你使用了keras预定义的mean_absolute_error（可简写为mse）应该是没问题的，所以可能是你最后网络输出的值有问题，有可能是一个列表，有可能是None。
建议：
1. 可尝试输出网络的输出结果，看看它是什么
2. 可修改源代码目标函数部分，输出一下目标函数的两个参数分别是什么，看看是哪个参数有问题

**Comment by boozyguo** [comment]
尝试输出了网络的输出结果，打印如下：输入是5336个数据长度为12，结果是5336个数据长度为1。

((5336L, 12L), 'test data samples')
((5336L, 1L), 'test results samples')
((5336L, 1L), 'predict samples')

**Comment by MoyanZitto** [comment]
@boozyguo 
这个结果的shape符合预期，其内容呢？5336个值是正常的数字还是包含“None”？
如果没问题建议在报错的地方加print输出结果。

**Comment by boozyguo** [comment]
@MoyanZitto 
对于输入，每个sample都是有值的。
对于输出，其实还有运行到，因此报错是在网络summry之后就出现了：

Using Theano backend.
42211
train mean and std
-5.7412179007e-15
0.999998773737
24.8304768035
-1.43510377268
((42211L, 12L), 'train samples')
((42211L, 1L), 'train samples')
[[-1.32533729 -1.33056343 -1.313815   -1.34508312 -0.19572419 -0.27889976
  -1.32741213 -1.32537913 -1.30741358 -1.33974254  0.08851133 -0.18669106]
 [-1.32678378 -1.32477272 -1.30679667 -1.33912539  0.08852199 -0.18675798
  -1.32741213 -1.32827556 -1.31303036 -1.34123254 -0.25545686 -0.29690933]
 [-1.32678378 -1.32766807 -1.31241131 -1.3406148  -0.25537726 -0.29693398
  -1.33175337 -1.32682741 -1.31443465 -1.34570265 -0.19187035 -0.27836755]
 [-1.33112311 -1.32622039 -1.313815   -1.34508312 -0.1918035  -0.27839932
  -1.33030629 -1.33117211 -1.31583881 -1.34421253 -0.32717445 -0.31986517]
 [-1.32967663 -1.33056343 -1.31521869 -1.3435936  -0.32708049 -0.31988102
  -1.32741213 -1.32972383 -1.31303036 -1.34123254 -0.20366362 -0.2807031 ]]
[[ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]]
5336
train mean and std
1.08447e-09
0.999999
24.8305
-1.4351
((5336L, 12L), 'test samples')
((5336L, 1L), 'test samples')

---

# Layer (type)                     Output Shape          Param #     Connected to                     

dense_1 (Dense)                  (None, 16)            208         dense_input_1[0][0]              

---

activation_1 (Activation)        (None, 16)            0           dense_1[0][0]                    

---

dropout_1 (Dropout)              (None, 16)            0           activation_1[0][0]               

---

dense_2 (Dense)                  (None, 1)             17          dropout_1[0][0]                  

---

# activation_2 (Activation)        (None, 1)             0           dense_2[0][0]                    

Total params: 225

---

Traceback (most recent call last):
  File "D:/working/AI/keras/snn/deepS/sys/deeps_mlp_github.py", line 130, in <module>
    validation_data=(x_test, y_test))
  File "C:\Anaconda2\lib\site-packages\keras\models.py", line 429, in fit
    sample_weight=sample_weight)
  File "C:\Anaconda2\lib\site-packages\keras\engine\training.py", line 1081, in fit
    self._make_train_function()
  File "C:\Anaconda2\lib\site-packages\keras\engine\training.py", line 698, in _make_train_function
    training_updates = self.optimizer.get_updates(trainable_weights, self.constraints, self.total_loss)
  File "C:\Anaconda2\lib\site-packages\keras\optimizers.py", line 321, in get_updates
    grads = self.get_gradients(loss, params)
  File "C:\Anaconda2\lib\site-packages\keras\optimizers.py", line 53, in get_gradients
    grads = K.gradients(loss, params)
  File "C:\Anaconda2\lib\site-packages\keras\backend\theano_backend.py", line 576, in gradients
    return T.grad(loss, variables)
  File "C:\Anaconda2\lib\site-packages\theano\gradient.py", line 436, in grad
    raise TypeError("cost must be a scalar.")
TypeError: cost must be a scalar.

Process finished with exit code 1
